#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER $POSTGRES_DB <<-EOSQL
CREATE EXTENSION postgis;
CREATE TABLE ddl_info( id SERIAL, version INT, installed TIMESTAMP );

GRANT SELECT,INSERT,UPDATE,DELETE ON ddl_info TO $POSTGRES_USER;
GRANT USAGE ON SEQUENCE ddl_info_id_seq TO $POSTGRES_USER;

CREATE OR REPLACE FUNCTION isnumeric(text) RETURNS BOOLEAN AS \$\$
DECLARE x NUMERIC;
BEGIN
    x = \$1::NUMERIC;
    RETURN TRUE;
EXCEPTION WHEN others THEN
    RETURN FALSE;
END;
\$\$ LANGUAGE plpgsql IMMUTABLE;
EOSQL
