IF db_id('${DATABASE}') IS NULL
BEGIN
  CREATE DATABASE ${DATABASE};
END
GO

IF db_id('${DATABASE}') IS NULL
BEGIN
  USE BigSense
  CREATE LOGIN ${DB_USER} WITH PASSWORD=N'${DB_PASSWORD}', DEFAULT_DATABASE=${DATABASE}, CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;
  CREATE USER ${DB_USER} FOR LOGIN ${DB_USER};
  EXEC sp_addrolemember N'db_owner', N'${DB_USER}';
END
GO
